

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_MY_LOCATIONS = 'SET_MY_LOCATIONS';
export const SET_TIME_DESIGN = 'SET_TIME_DESIGN';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';